name: Manually Trigger Update All Branches

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest changes from origin master
        run: git fetch origin master

      - name: Update branches
        run: |
          # Get a list of all branches excluding master
          branches=$(git branch --no-color | grep -v "master")

          # Print branches for debugging
          echo "Branches: $branches"

          # Loop through each branch and update it if it's behind master
          for branch in $branches; do
            if git merge-base --is-ancestor origin/master $branch; then
              echo "$branch is up-to-date with master."
            else
              echo "Updating $branch with latest changes from master."
              git checkout $branch
              git merge origin/master
              git push origin $branch
            fi
          done
