name: Manually Trigger Update All Branches

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update branches
        run: |
          # Pull the latest changes from origin master
          git pull origin master

          # Get a list of all branches excluding master
          branches=$(git branch --no-color | grep -v master)

          # Loop through each branch and update it
          for branch in $branches; do
            git checkout $branch
            git merge master
            git push origin $branch
          done

          # Switch back to master branch
          git checkout master

      - name: Check if branches are up-to-date
        run: |
          branches=$(git branch --no-color | grep -v master)

          for branch in $branches; do
            if git merge-base --is-ancestor $branch master; then
              echo "$branch is up-to-date with master."
            else
              echo "ALERT: $branch is behind master. Please update."
              exit 1
            fi
          done
